# Generated by Django 6.0.6 on 2026-06-16 21:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('voluntario', 'Voluntário'), ('ong', 'ONG')], default='voluntario', max_length=20)),
                ('cnpj', models.CharField(blank=True, help_text='Somente para ONGs', max_length=18, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ inválido')])),
                ('nome_organizacao', models.CharField(blank=True, max_length=200)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de perfil')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ONG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=1000)),
                ('localizacao', models.CharField(max_length=200)),
                ('emoji', models.CharField(default='🌟', max_length=10)),
                ('ativa', models.BooleanField(default=True)),
                ('urgente', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='ongs', to='core.categoria')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ongs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ONG',
                'verbose_name_plural': 'ONGs',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alimento', 'Alimentos'), ('roupa', 'Roupas e Calçados'), ('movel', 'Móveis e Eletrodomésticos'), ('brinquedo', 'Brinquedos'), ('livro', 'Livros e Material Escolar'), ('higiene', 'Higiene e Limpeza'), ('remedio', 'Remédios'), ('dinheiro', 'Dinheiro / PIX'), ('outro', 'Outro')], max_length=30)),
                ('descricao', models.TextField(help_text='Detalhe o que precisa exatamente', max_length=500)),
                ('urgente', models.BooleanField(default=False)),
                ('ativa', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='core.ong')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-urgente', '-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, max_length=500)),
                ('disponibilidade', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to=settings.AUTH_USER_MODEL)),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.ong')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-criada_em'],
                'unique_together': {('usuario', 'ong')},
            },
        ),
    ]
